[package]
name = "iced_servo"
version = "0.1.0"
edition = "2024"
description = "An easily embedded servo webview library for iced"
authors = [
  "LegitCamper",
  "Franz Geffke <mail@gofranz.com>",
  "Vitalii Lukyanov <tukanoid@outlook.com>",
]
repository = "https://github.com/tukanoidd/iced_servo/"
license = "Apache-2.0"
readme = "README.md"

[lib]
name = "iced_servo"

[package.metadata.docs.rs]
features = ["docs_only"]
all-features = false
no-default-features = true

[profile.dev]
incremental = true
opt-level = "s"
lto = "thin"

[features]
default = []
docs_only = []

[dependencies]
iced = { version = "0.14", features = ["advanced", "image", "tokio", "lazy"] }

tokio = { version = "1", features = ["rt", "sync"] }

rand = "0.10"
url = "2.5"
smol_str = { version = "0.3", optional = true }

# Servo engine deps
servo = { version = "0.3", features = ["webgpu"] }
urlencoding = "2"
rustls = { version = "0.23", default-features = false, features = [
  "logging",
  "std",
  "tls12",
  "aws_lc_rs",
] }
euclid = "0.22"
keyboard-types = "0.8"
dpi = "0.1"

[[example]]
name = "webview"

[[example]]
name = "email"

[[example]]
name = "embedded_webview"
